// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plbuldvrrgkazzyogdac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYnVsZHZycmdrYXp6eW9nZGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NzY1MjIsImV4cCI6MjA3MDQ1MjUyMn0.E5OSpOuUDg2IicnRDY5yY6rDFaexuSU2xpGn_kru6W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});